---
- name: Préparer l'environnement de déploiement
  hosts: servers
  become: yes

  tasks:
    - name: Installer Terraform via script
      shell: |
        apt-get update -y
        apt-get install -y gnupg software-properties-common curl
        curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --yes --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
        apt-get update -y
        apt-get install -y terraform
      args:
        executable: /bin/bash

    - name: Vérifier Docker est disponible
      command: docker --version
      register: docker_version

    - name: Vérifier Terraform est installé
      command: terraform -v
      register: terraform_version

    - name: Afficher les versions
      debug:
        msg:
          - "{{ docker_version.stdout }}"
          - "{{ terraform_version.stdout }}"